### ISSUE TITLE
'primary' of undefined

### ISSUE THREAD

**Issue by hamzahio** [pubkey/rxdb#15]
when i try to add to my project always give me this error.
I just add script tag;

```
Uncaught TypeError: Cannot read property 'primary' of undefined
    at checkField (http://localhost:4200/rxdb.js:2370:26)
    at traverse (http://localhost:4200/rxdb.js:2384:17)
    at traverse (http://localhost:4200/rxdb.js:2388:13)
    at traverse (http://localhost:4200/rxdb.js:2388:13)
    at validateFieldsDeep (http://localhost:4200/rxdb.js:2391:5)
    at checkSchema (http://localhost:4200/rxdb.js:2406:5)
    at Object.create (http://localhost:4200/rxdb.js:2461:5)
    at Object.1../RxSchema (http://localhost:4200/rxdb.js:15:56)
    at s (http://localhost:4200/rxdb.js:1:254)
    at http://localhost:4200/rxdb.js:1:305checkField @ rxdb.js:2370traverse @ rxdb.js:2384traverse @ rxdb.js:2388traverse @ rxdb.js:2388validateFieldsDeep @ rxdb.js:2391checkSchema @ rxdb.js:2406create @ rxdb.js:24611../RxSchema @ rxdb.js:15s @ rxdb.js:1(anonymous function) @ rxdb.js:15../Database.schemas @ rxdb.js:917s @ rxdb.js:1(anonymous function) @ rxdb.js:110../PouchDB @ rxdb.js:2529s @ rxdb.js:1(anonymous function) @ rxdb.js:19../index.js @ rxdb.js:2467s @ rxdb.js:1e @ rxdb.js:1(anonymous function) @ rxdb.js:1
```

**Comment by pubkey** [comment]
Hi @hamzahio there is a problem with the rollup-build. Use [this](https://github.com/pubkey/rxdb/blob/master/dist/rxdb.browserify.min.js) file instead.
