### ISSUE TITLE
Sort error, pouchdb-find/mango "unknown operator"

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#164]
Apologies for opening all these issues!

## Case
https://www.webpackbin.com/bins/-KjpgcHUKURB4JtitaYe

## Code
```js
import React from 'react'
import {render} from 'react-dom'
import 'base64-js'
import 'ieee754'
import 'isarray'
import 'rxjs'
import * as RxDB from 'rxdb'
import pIDB from 'pouchdb-adapter-idb'

RxDB.plugin(pIDB)

render(<div>see console</div>,document.querySelector('#app') )

RxDB.create({
  adapter: 'idb',
  name: 'user',
  password: 'password'
})
.then(db => db.collection({
  name: 'test3',
  schema: { title: 'test3', version: 0, properties: { name: { type: 'string', index: true } } }
}))
.then(collection => {
  console.log('got', collection)
  collection.insert({ name: '1233'  })
  collection.insert({ name: '12344'  })
  collection.find({ sort: ['name'] }).exec().then(console.log)
})
```

Error:
```
Uncaught (in promise) Error: unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type or $all
    at match (https://cdn.jsdelivr.net/webpack/v2/base64-js%401.2.0%2Bieee754%401.1.8%2Bi…om%4015.4.2%2Breact%4015.4.2%2Brxdb%404.0.0%2Brxjs%405.4.0/dll.js:17732:11)
    at https://cdn.jsdelivr.net/webpack/v2/base64-js%401.2.0%2Bieee754%401.1.8%2Bi…om%4015.4.2%2Breact%4015.4.2%2Brxdb%404.0.0%2Brxjs%405.4.0/dll.js:17707:12
    at Array.every (native)
    at matchSelector (https://cdn.jsdelivr.net/webpack/v2/base64-js%401.2.0%2Bieee754%401.1.8%2Bi…om%4015.4.2%2Breact%4015.4.2%2Brxdb%404.0.0%2Brxjs%405.4.0/dll.js:17705:31)
    at https://cdn.jsdelivr.net/webpack/v2/base64-js%401.2.0%2Bieee754%401.1.8%2Bi…om%4015.4.2%2Breact%4015.4.2%2Brxdb%404.0.0%2Brxjs%405.4.0/dll.js:17691:12
    at Array.every (native)
    at rowFilter (https://cdn.jsdelivr.net/webpack/v2/base64-js%401.2.0%2Bieee754%401.1.8%2Bi…om%4015.4.2%2Breact%4015.4.2%2Brxdb%404.0.0%2Brxjs%405.4.0/dll.js:17679:25)
    at https://cdn.jsdelivr.net/webpack/v2/base64-js%401.2.0%2Bieee754%401.1.8%2Bi…om%4015.4.2%2Breact%4015.4.2%2Brxdb%404.0.0%2Brxjs%405.4.0/dll.js:17656:12
    at Array.filter (native)
    at Object.filterInMemoryFields (https://cdn.jsdelivr.net/webpack/v2/base64-js%401.2.0%2Bieee754%401.1.8%2Bi…om%4015.4.2%2Breact%4015.4.2%2Brxdb%404.0.0%2Brxjs%405.4.0/dll.js:17655:15)
```

**Comment by natew** [comment]
I know the chained `.sort()` can be used, but the object notation is actually really helpful for our stack. It lets use parameterize arguments and cache things, as well as gives more flexible api's to your functions (can pass in an object rather than some sort of cb + chain like `query => query.sort()...`)

**Comment by pubkey** [comment]
This is a bug. Fix will come.
Please note that `RxCollection.insert` is an async function. 
If you do 
```js
  collection.insert({ name: '1233'  })
  collection.insert({ name: '12344'  })
  collection.find({ sort: ['name'] }).exec().then(console.log)
```
then the query will probably not find the two inserted documents. (depending on which storage-engine you use)

**Comment by pubkey** [comment]
I could not reproduce this at the test. I don't know if it's an RxDB issue.
Reopen if you have more information.

**Comment by natew** [comment]
I still see this btw on the webpackbin: https://jsfiddle.net/h8n0awfc/, open the console and I get this error:

![image](https://cloud.githubusercontent.com/assets/12100/26364681/f5ed0438-3f99-11e7-9a3c-3e6200b7a6f4.png)

**Comment by pubkey** [comment]
Ok i found the issue. As described [in the docs](https://pubkey.github.io/rxdb/RxCollection.html), `RxCollection.find()` only takes the selector, not the conditions. You cannot pass sort here. Use the sort-function.

**Comment by natew** [comment]
Actually, just looked at that doc page and it's not mentioned. Want me to add it?
