### ISSUE TITLE
Server plugin spawn error: TypeError: ExpressPouchDB is not a function

### ISSUE THREAD

**Issue by mtenrero** [pubkey/rxdb#1886]
## Case
Bug

## Issue
Using Server plugin can't spawn a server and the following error appears:

```bash
Since version 8.4.0 the module 'express-pouchdb' is not longer delivered with RxDB.
You can install it with 'npm install express-pouchdb'
start server
(node:12400) UnhandledPromiseRejectionWarning: TypeError: ExpressPouchDB is not a function
    at RxDatabaseBase.spawnServer [as server] (C:\Users\marcostm\Documents\personal\vetio-react\.webpack\main\index.js:60938:28)
    at C:\Users\marcostm\Documents\personal\vetio-react\.webpack\main\index.js:85864:12
    at Generator.next (<anonymous>)
(node:12400) UnhandledPromiseRejectionWarning: TypeError: ExpressPouchDB is not a function
    at RxDatabaseBase.spawnServer [as server] (C:\Users\marcostm\Documents\personal\vetio-react\.webpack\main\index.js:60938:28)
    at C:\Users\marcostm\Documents\personal\vetio-react\.webpack\main\index.js:85864:12
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\marcostm\Documents\personal\vetio-react\.webpack\main\index.js:85803:58)
(node:12400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
webpack built 5821e72debe816169520 in 2336ms
```
Express-pouchdb is already added in the dependency list.

**database.ts**
```ts
import RxDB, { RxDatabase, CollectionsOfDatabase } from 'rxdb';

import ServerPlugin from 'rxdb/plugins/server';

RxDB.plugin(require('pouchdb-adapter-http'));
RxDB.plugin(require('pouchdb-adapter-leveldb'));
RxDB.plugin(ServerPlugin);

class Database {
    name: string;
    _database : Promise<RxDatabase<CollectionsOfDatabase>>;

    constructor(name: string) {
        this.name = name;

        this._database = this._createDatabase(name, 'leveldb');
    }

    getDatabaseInstance() {
        return this._database;
    }

    private async _createDatabase(name: string, adapter: string) {
        const db = RxDB.create({
            name,
            adapter,
            password: 'myLongAndStupidPassword'
        });

        return db;
    }
}

export {
    Database
}
```

**main.ts**
```ts
    const dbInstance = new Database('mivet_local');
    const db = await dbInstance.getDatabaseInstance();

    db.server({
        path: '/db',
        port: 10102,
        cors: true
    });
```

## Info
  - Environment: Electron 7.1.10 + webpack
  - Adapter: LevelDB / leveldown
  - Stack: Typescript

## Code
**package.json***
```json
{
...
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.47",
    "@electron-forge/maker-deb": "^6.0.0-beta.47",
    "@electron-forge/maker-rpm": "^6.0.0-beta.47",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.47",
    "@electron-forge/maker-zip": "^6.0.0-beta.47",
    "@electron-forge/plugin-webpack": "^6.0.0-beta.47",
    "@marshallofsound/webpack-asset-relocator-loader": "^0.5.0",
    "css-loader": "^3.4.2",
    "electron": "7.1.10",
    "electron-builder": "^22.3.2",
    "electron-rebuild": "^1.10.0",
    "node-loader": "^0.6.0",
    "style-loader": "^1.1.3",
    "ts-loader": "^6.2.1"
  },
  "dependencies": {
    "@types/react": "^16.9.19",
    "@types/react-dom": "^16.9.5",
    "electron-squirrel-startup": "^1.0.0",
    "express-pouchdb": "^4.2.0",
    "fork-ts-checker-webpack-plugin": "^4.0.3",
    "pouchdb-adapter-http": "^7.1.1",
    "pouchdb-adapter-leveldb": "^7.1.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "rxdb": "^8.7.5",
    "typescript": "^3.7.5"
  }
}
```

**Comment by pubkey** [comment]
check your node_modules folder if the plugin is there. If not run npm install.

**Comment by mtenrero** [comment]
> 
> 
> check your node_modules folder if the plugin is there. If not run npm install.

The package is also present in node_modules

**Comment by pubkey** [comment]
Ok this looks like an issue then.
Can you try to reproduce the problem in the [rxdb electron example](https://github.com/pubkey/rxdb/tree/master/examples/electron)?

**Comment by rbarisic-lme** [comment]
Any update on this?

**Comment by joe307bad** [comment]
I am also seeing this error. I downgraded to `8.6.0` and still see the error. I will spend some time in the near future creating a repo that reproduces this error.

**Comment by joe307bad** [comment]
@pubkey [Here is a repo](https://github.com/joe307bad/electron-with-rxdb) that reproduces the error in a minimal electron + react + webpack repo.

**Comment by pubkey** [comment]
@joe307bad in your repo, express-pouchdb is missing in the dependencies.

**Comment by joe307bad** [comment]
Thanks for the quick response @pubkey! That worked! I could've sworn I ran into this issue in another project and it had `express-pouchdb`. I will post again if I see it again.

**Comment by joe307bad** [comment]
@pubkey here is another [example repo](https://github.com/joe307bad/electron-with-ts-and-rxdb) where I see this error. It's as minimalistic as I could get an example that includes Electron + webpack + Typescript.

**Comment by joe307bad** [comment]
Whenever I log the error that is thrown [here](https://github.com/pubkey/rxdb/blob/master/dist/lib/plugins/server.js#L36-L39) and I get this error:
```
TypeError: Promise.resolve is not a function
    at eval (webpack:///./node_modules/express-pouchdb/lib/daemon-manager.js?:6:24)
    at Object../node_modules/express-pouchdb/lib/daemon-manager.js (/Users/joe307bad/Source/electron-with-ts-and-rxdb/output/compiled/main/main-bundle.js:6007:1)
    at __webpack_require__ (/Users/joe307bad/Source/electron-with-ts-and-rxdb/output/compiled/main/main-bundle.js:20:30)
    at eval (webpack:///./node_modules/express-pouchdb/lib/index.js?:6:23)
    at Object../node_modules/express-pouchdb/lib/index.js (/Users/joe307bad/Source/electron-with-ts-and-rxdb/output/compiled/main/main-bundle.js:6055:1)
    at __webpack_require__ (/Users/joe307bad/Source/electron-with-ts-and-rxdb/output/compiled/main/main-bundle.js:20:30)
    at eval (webpack:///./node_modules/rxdb/dist/es/plugins/server.js?:36:20)
    at Module../node_modules/rxdb/dist/es/plugins/server.js (/Users/joe307bad/Source/electron-with-ts-and-rxdb/output/compiled/main/main-bundle.js:10298:1)
    at __webpack_require__ (/Users/joe307bad/Source/electron-with-ts-and-rxdb/output/compiled/main/main-bundle.js:20:30)
    at eval (webpack:///./src/main/index.ts?:17:58)
```

So this may be a problem with `express-pouchdb`. I saw this error before and I tracked it down to `pouchdb-promise`. But I can't find the actual source for `pouchdb-promise`. I was only able to inspect it via my own `node_modules`.

**Comment by euroclydon37** [comment]
I also ran into the `TypeError: Promise.resolve is not a function` issue.
