### ISSUE TITLE
npm run transpile fails without Node > 7

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#195]
In new repo:

```npm run transpile

> motion-rxdb@5.0.0 transpile /Users/nw/projects/motion/rxdb
> node scripts/transpile.js

/Users/nw/projects/motion/rxdb/scripts/transpile.js:37
async function transpileFile(srcLocation, goalLocation) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! motion-rxdb@5.0.0 transpile: `node scripts/transpile.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the motion-rxdb@5.0.0 transpile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nw/.npm/_logs/2017-06-05T00_18_59_530Z-debug.log```

**Comment by natew** [comment]
Note for updating node should suffice! Didn't realize I was on an old version.

**Comment by pubkey** [comment]
Fixed [here](https://github.com/pubkey/rxdb/commit/2aea15cdf82b0ae474b3f04a2d30d39d23c3d9b9)
