### ISSUE TITLE
Throw error when using RxDBServerPlugin with leveldown/memdown

### ISSUE THREAD

**Issue by zxc122333** [pubkey/rxdb#2491]
## Case
BUG

## Issue
An error when using RxDBServerPlugin with leveldown/memdown
```
(node:49982) UnhandledPromiseRejectionWarning: Error: Invalid Adapter: function MemDOWN () {
  if (!(this instanceof MemDOWN)) return new MemDOWN()

  AbstractLevelDOWN.call(this, {
    bufferKeys: true,
    snapshots: true,
    permanence: false,
    seek: true,
    clear: true
  })

  this._store = createRBT(ltgt.compare)
}
    at PouchAlt.PouchDB (node_modules/pouchdb-core/lib/index.js:1292:11)
    at new PouchAlt (node_modules/pouchdb-core/lib/index.js:1412:13)
    at node_modules/express-pouchdb/lib/create-or-delete-dbs.js:30:10
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Info
  - Environment: Node.js 14.9.0
  - Adapter: memdown or leveldown
  - Stack: 

## Code

```js
const {addRxPlugin, createRxDatabase} = require("rxdb");
addRxPlugin(require("rxdb/plugins/server"));
addRxPlugin(require('pouchdb-adapter-leveldb'));
const memdown = require('memdown');

async function test(){
  const db = await createRxDatabase({
    name: 'mydb',
    adapter: memdown
  });
  // db.adapter = "leveldb";  // <-- This line will make it work, but I don't know if it will lead to other problems
  db.server({
    path: '/db',
    port: 3000,
    cors: true,
    startServer: true,
    pouchdbExpressOptions: {
      inMemoryConfig: true,
      logPath: '/tmp/rxdb-server-log.txt'
    }
  });
}

test().then(()=>{
    console.log("success!")
  },err=>{
    console.error(err)
  }
);
```

## Possible reason
[src/plugins/server.ts#L100](https://github.com/pubkey/rxdb/blob/000759b28743bc2575bcde5dfc4295db5dfc4f1d/src/plugins/server.ts#L100)
```js
const pseudo = PouchDB.defaults({
   adapter: db.adapter, // <-- db.adapter is the constructor of memdown
   prefix: getPrefix(db),
   log: false
});
```

[pouchdb-core/lib/index.js#2262](https://github.com/pouchdb/pouchdb/blob/5669a5d7366306682b487cf41ceab77de8066bee/lib/index.js#L2662)
```js
if (!PouchDB.adapters[opts.adapter] ||   // <--- use opt.adapter as string
  !PouchDB.adapters[opts.adapter].valid()) {
    throw new Error('Invalid Adapter: ' + opts.adapter);
}
```

**Comment by pubkey** [comment]
I checked, I also use `adapter: 'leveldb' which is likely why I havent stumpled over this before.
We have to find out if this is a problem with RxDB. It very likely must be fixed at the pouchdb-server repo.

**Comment by pubkey** [comment]
Closing this. I think this should be opened as pouchdb-server because that module does not allow adding non-string adapters.
