### ISSUE TITLE
Schema should allow primary and ref at the same time

### ISSUE THREAD

**Issue by beorn** [pubkey/rxdb#2747]
## Case

I'd like to have two collections be related through their id - e.g., a collection of nodes with the path for each node in a separate collection:

```js
    nodes: {
      schema: {
        version: 0,
        type: "object",
        properties: {
          id: { type: "string", primary: true },
        },
      },
    },
    paths: {
      schema: {
        version: 0,
        type: "object",
        properties: {
          id: { type: "string", ref: "nodes", primary: true },
        },
      },
    },
  })
```

## Issue

But it seems this is not possible - is there any reason for this?

```console
Uncaught (in promise) RxError (SC5): RxError:
SchemaCheck: fieldname cannot be primary and ref at same time
Given parameters: {
fieldName:"id"}
    at newRxError (http://localhost:3000/server/index.js:71151:10)
    at checkField (http://localhost:3000/server/index.js:64260:73)
    at http://localhost:3000/server/index.js:64301:9
    at Array.forEach (<anonymous>)
    at traverse (http://localhost:3000/server/index.js:64299:29)
    at http://localhost:3000/server/index.js:64306:7
    at Array.forEach (<anonymous>)
    at traverse (http://localhost:3000/server/index.js:64299:29)
    at validateFieldsDeep (http://localhost:3000/server/index.js:64310:3)
    at checkSchema (http://localhost:3000/server/index.js:64358:3)
```

I would of course be responsible for setting the id when creating items.

## Info
  - Environment: Electron 11.0.3 renderer (Chrome M87)
  - Adapter: IndexedDB
  - Stack: Typescript, React, electron-forge

**Comment by pubkey** [comment]
Yes that makes sense. I have no idea why I included this check.

**Comment by pubkey** [comment]
Can you make a PR with a test case?

**Comment by pubkey** [comment]
I solved this in the linked commit.
