### ISSUE TITLE
v12.7.15 Tests don't pass on Windows 10

### ISSUE THREAD

**Issue by Smolations** [pubkey/rxdb#3953]
1. I can't create a PR because all I did was clone this repo on my machine and run `npm test`. 
2. I recognize that this may indeed actually be an issue for [karma-edge-launcher](https://github.com/karma-runner/karma-edge-launcher/issues/7) but you should be aware that your test suite is currently failing on windows.

<details>
<summary>the node version and `npm i`</summary>

```
10:09PM C:\Users\Smola\projects\rxdb> nvm use v18.4.0
Now using node v18.4.0 (64-bit)
10:09PM C:\Users\Smola\projects\rxdb> node -v
v18.4.0
10:09PM C:\Users\Smola\projects\rxdb> git status
On branch v12.7.16
nothing to commit, working tree clean
10:11PM C:\Users\Smola\projects\rxdb> npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@36.1.1',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.4.0', npm: '8.12.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.10.8',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16' },
npm WARN EBADENGINE   current: { node: 'v18.4.0', npm: '8.12.1' }
npm WARN EBADENGINE }
npm WARN deprecated flatten@0.0.1: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated flat@1.0.0: Fixed a prototype pollution security issue in flat, please upgrade to ^1.6.2 or ^5.0.1.
npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @babel/polyfill@7.12.1: � This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when
needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated subscriptions-transport-ws@0.11.0: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

> rxdb@12.7.15 postinstall
> node scripts/postinstall.js || echo "ignore"


added 1605 packages, and audited 2163 packages in 2m

146 packages are looking for funding
  run `npm fund` for details

62 vulnerabilities (4 low, 25 moderate, 24 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
</details>

<details>
<summary>sometime after running `npm test`:</summary>

```
10:11PM C:\Users\Smola\projects\rxdb> npm test
# ...
  845 passing (1m)


> rxdb@12.7.15 test:browser C:\Users\Smola\projects\rxdb
> npm run transpile && cross-env DEFAULT_STORAGE=pouchdb karma start ./config/karma.conf.js --single-run


> rxdb@12.7.15 transpile C:\Users\Smola\projects\rxdb
> node scripts/transpile.js

# transpiling.. (this takes some time on first run)
Successfully compiled 3 files with Babel (3568ms).
Successfully compiled 1 file with Babel (3330ms).
Successfully compiled 2 files with Babel (3458ms).
Successfully compiled 2 files with Babel (3907ms).
Successfully compiled 3 files with Babel (3594ms).
Successfully compiled 9 files with Babel (3664ms).
Successfully compiled 8 files with Babel (4210ms).
Successfully compiled 3 files with Babel (4227ms).
Successfully compiled 5 files with Babel (4491ms).
Successfully compiled 9 files with Babel (3753ms).
Successfully compiled 4 files with Babel (4596ms).
Successfully compiled 10 files with Babel (4048ms).
Successfully compiled 6 files with Babel (4687ms).
Successfully compiled 5 files with Babel (4753ms).
Successfully compiled 11 files with Babel (4950ms).
Successfully compiled 4 files with Babel (4639ms).
Successfully compiled 18 files with Babel (4345ms).
Successfully compiled 2 files with Babel (4253ms).
Successfully compiled 8 files with Babel (5100ms).
Successfully compiled 4 files with Babel (5064ms).
Successfully compiled 4 files with Babel (4674ms).
Successfully compiled 8 files with Babel (5031ms).
Successfully compiled 7 files with Babel (4756ms).
Successfully compiled 26 files with Babel (6065ms).
Successfully compiled 57 files with Babel (13331ms).
# transpiling DONE (20 CPUs)
25 08 2022 22:24:27.336:INFO [framework.detect-browsers]: The following browsers will be used: [ 'Chrome', 'Edge', 'IE' ]
25 08 2022 22:24:35.586:INFO [framework.browserify]: bundle built
25 08 2022 22:24:35.644:INFO [karma-server]: Karma v6.4.0 server started at http://localhost:9876/
25 08 2022 22:24:35.645:INFO [launcher]: Launching browsers Chrome, Edge, IE with concurrency unlimited
25 08 2022 22:24:35.653:INFO [launcher]: Starting browser Chrome
25 08 2022 22:24:35.681:INFO [launcher]: Starting browser Edge
25 08 2022 22:24:35.795:INFO [launcher]: Starting browser IE
25 08 2022 22:24:36.309:INFO [Chrome 104.0.5112.102 (Windows 10)]: Connected on socket FxZPpoQ3I9pSiJ_JAAAB with id 68847375
25 08 2022 22:24:36.530:INFO [IE 11.0 (Windows 10)]: Connected on socket JHEXqP0-_VsRqts-AAAD with id 92891254
IE 11.0 (Windows 10) ERROR
  Expected identifier, string or number
  at c:/Users/Smola/AppData/Local/node_modules/abstract-leveldown/abstract-chained-batch.js:36:1 <- C:/Users/Smola/AppData/Local/Temp/f780116bb20757ed536f8aa74257a2a4.browserify.js:25174:27


Chrome 104.0.5112.102 (Windows 10) LOG: 'DEFAULT_STORAGE: pouchdb'

Chrome 104.0.5112.102 (Windows 10) LOG: '# use RxStorage: pouchdb'

Chrome 104.0.5112.102 (Windows 10) LOG: '######## init.test.js ########'

Chrome 104.0.5112.102 (Windows 10) LOG: '###### PLATFORM: ######'

Chrome 104.0.5112.102 (Windows 10) LOG: 'USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36'

Chrome 104.0.5112.102 (Windows 10) LOG: 'PLATFORM-NAME: chrome'

Chrome 104.0.5112.102 (Windows 10) LOG: 'PLATFORM-VERSION: 104.0.5112'

Chrome 104.0.5112.102 (Windows 10) LOG: 'STORAGE: pouchdb'

WARN: 'WebSQL is deprecated and will be removed in future releases of PouchDB. Please migrate to IndexedDB: https://pouchdb.com/2018/01/23/pouchdb-6.4.2.html'
WARN: 'Attachment', 'myText', 'on document', 'myDoc', 'is missing content_type'
WARN: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/events/events.js:211:1)
    at PouchDB.addListener (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/events/events.js:227:1)
    at PouchDB.once (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/events/events.js:257:1)
    at new Changes (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/pouchdb-core/lib/index.js:51:1)
    at PouchDB.AbstractPouchDB.changes (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/pouchdb-core/lib/index.js:954:1)
    at Changes.eventFunction (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/pouchdb-utils/lib/index-browser.js:412:1)
    at Changes.emit (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/events/events.js:158:1)
    at Changes.notify (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/pouchdb-utils/lib/index-browser.js:449:1)
    at PouchDB.LevelPouch.api._changes (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/pouchdb-adapter-leveldb-core/lib/index-browser.js:1057:1)
    at Changes.doChanges (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/pouchdb-core/lib/index.js:197:1)
    at http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/pouchdb-core/lib/index.js:167:1
LOG: 'here', false
LOG: 'here', false
LOG: 'here', false
Chrome 104.0.5112.102 (Windows 10): Executed 370 of 852 SUCCESS (0 secs / 18.667 secs)
25 08 2022 22:24:57.214:ERROR [launcher]: Killing Edge process failed. Error: Command failed: taskkill /t /f /im MicrosoftEdge.exe
ERROR: The process "MicrosoftEdge.exe" not found.

25 08 2022 22:24:57.215:ERROR [launcher]: Cannot start Edge
        undefined
25 08 2022 22:24:57.216:ERROR [launcher]: Edge stdout:
Couldn't find Edge URL with URL: 014EF658
Found
25 08 2022 22:24:57.217:ERROR [launcher]: Edge stderr:
LOG: 'here', false
Chrome 104.0.5112.102 (Windows 10): Executed 660 of 852 SUCCESS (0 secs / 38.554 secs)
25 08 2022 22:25:18.602:ERROR [launcher]: Killing Edge process failed. Error: Command failed: taskkill /t /f /im MicrosoftEdge.exe
ERROR: The process "MicrosoftEdge.exe" not found.

25 08 2022 22:25:18.603:ERROR [launcher]: Cannot start Edge
        undefined
25 08 2022 22:25:18.604:ERROR [launcher]: Edge stdout:
Couldn't find Edge URL with URL: 010FF498
Found
25 08 2022 22:25:18.607:ERROR [launcher]: Edge stderr:
Chrome 104.0.5112.102 (Windows 10): Executed 819 of 852 SUCCESS (0 secs / 56.668 secs)
25 08 2022 22:25:39.988:ERROR [launcher]: Killing Edge process failed. Error: Command failed: taskkill /t /f /im MicrosoftEdge.exe
ERROR: The process "MicrosoftEdge.exe" not found.

25 08 2022 22:25:39.990:ERROR [launcher]: Cannot start Edge
        undefined
25 08 2022 22:25:39.990:ERROR [launcher]: Edge stdout:
Couldn't find Edge URL with URL: 00AEF498
Found
25 08 2022 22:25:39.991:ERROR [launcher]: Edge stderr:
WARN: 'db.type() is deprecated and will be removed in a future version of PouchDB'
WARN: 'db.type() is deprecated and will be removed in a future version of PouchDB'
WARN: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/events/events.js:211:1)
    at PouchDB.addListener (http://localhost:9876/absoluteC:/Users/Smola/AppData/Local/node_modules/events/events.js:227:1)
```
</details>

As for what happens on my machine for the above, or more directly, `npm run test:browser`, I see chrome open up with a karma status, and Edge open with a tab, then another tab in 10seconds or so, then another tab in another 10 seconds or so, then the process dies. None of the Edge processes are ever successfully killed and subsequent tests do not appear to get run.

Again, given that this is ultimately likely to be not your problem, feel free to close. This is more-or-less just a notification (and I did post in the discord but received no response after 24hrs).

**Comment by pubkey** [comment]
Thank you for investigating.
I removed the edge launcher now. It looks like it is outdated anyway and the last release is 5 years old.

**Comment by Smolations** [comment]
@pubkey Would it be possible to add an additional tag on the stable branch with this change so I can re-test?

**Comment by pubkey** [comment]
Add it to your local branch please.
