### ISSUE TITLE
Issues while calling attatchment.getData()

### ISSUE THREAD

**Issue by ravi-poonia-lib** [pubkey/rxdb#3984]
Issues while pulling attachment in main electron process:

ReferenceError: Blob is not defined
    at node_modules/rxdb/src/plugins/pouchdb/rx-storage-instance-pouch.ts:295:13
    
   rxdb: 13.0.3

**Comment by ravi-poonia-lib** [comment]
I addeed blob-polyfill package and added that to global like:
`global['Blob'] = Blob;
`
Now I'm getting:

```
ReferenceError: fetch is not defined
    at Object.createBlobBufferFromBase64 (node_modules/rxdb/src/util.ts:615:28)
    at node_modules/rxdb/src/plugins/attachments.ts:130:42
```

Is attachment.getData() not supposed to used in the main process?
