### ISSUE TITLE
Error on examples/vanilla RxDB.getRxStoragePouch is not a function  at main.js:34:23

### ISSUE THREAD

**Issue by ridwanskaterock** [pubkey/rxdb#4176]
### Case
use cd examples/vanilla
npm i 
npm start 

I got this message `RxDB.getRxStoragePouch is not a function
    at main.js:34:23`

![image](https://user-images.githubusercontent.com/9270445/207068336-7ae107eb-4245-4628-a98e-56f4d564e57c.png)

I think for vanilla examples i out of date ?

**Comment by pubkey** [comment]
Yes it os oit of date. Pls make a PR
