### ISSUE TITLE
SQLite cannot find by `number`

### ISSUE THREAD

**Issue by jwallet** [pubkey/rxdb#4571]
RxSQLiteStorage cannot extract data using a number,

```ts
// define your schema
const mySchema = {
  version: 0,
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    age: {
      type: 'integer',
    },
  },
  required: ['name', 'age'],
};

// create database

// create a collection
const myCollection = await myDatabase.collection({
  name: 'mycollection',
  schema: mySchema,
});

// insert a document into the collection
const myInsertDoc = await myCollection.insert({
  name: 'John',
  age: 30,
});

// find it by its age
const myDocFound = await myCollection.find({
  selector: {
    age: { $eq: 30 },
  }
}).exec();

assert.deepEqual(myInsertDoc.toJson(), myDocFound.toJson()); // myDocFound contains no element
```

Looks like there is an issue when using your `sqlite-helpers` `getJsonExtract` 

apparently, to use `JSON_EXTRACT` with a `number`, it should be `CAST` to `INTEGER , anyway... maybe the bug is somewhere else

```sql
CAST(JSON_EXTRACT(my_column, '$.my_key') AS INTEGER)
```

**Comment by jwallet** [comment]
same thing goes for `boolean` 

```
SELECT * FROM my_table WHERE CAST(JSON_EXTRACT(my_column, '$.my_boolean') AS INTEGER) = 1;
```

**Comment by jwallet** [comment]
a note that casting a number containing precision will need to be cast as `REEL` might as well use that one instead.

**Comment by pubkey** [comment]
Your schema is missing the primaryKey field.
Which RxDB version are you using?
I added some tests here a0bc151f0aac3fefc22ef679179b86ee5a927a93 and run them with the SQLite RxStorage, but there everything worked.

Also I added the following test to the SQLite RxStorage test suite and everything worked correctly.

```ts
                const mySchema: RxJsonSchema<any> = {
                    version: 0,
                    type: 'object',
                    primaryKey: 'name',
                    properties: {
                        name: {
                            type: 'string',
                            maxLength: 40
                        },
                        age: {
                            type: 'integer',
                        },
                    },
                    required: ['name', 'age'],
                };

                // create database
                const collectionName = randomCouchString(10);
                const myDatabase = await createRxDatabase<{ human: RxCollection<TestDocType> }>({
                    name: SQLITE_IN_MEMORY_DB_NAME,
                    storage,
                    multiInstance: false
                });

                // create a collection
                const collections = await myDatabase.addCollections({
                    [collectionName]: {
                        schema: mySchema,
                    }
                });
                const myCollection: RxCollection = collections[collectionName];

                // insert a document into the collection
                const myInsertDoc = await myCollection.insert({
                    name: 'John',
                    age: 30,
                });

                // find it by its age
                const queryResult = await myCollection.find({
                    selector: {
                        age: { $eq: 30 },
                    }
                }).exec();
                const myDocFound = ensureNotFalsy(queryResult[0]);

                assert.deepEqual(myInsertDoc.toJSON(), myDocFound.toJSON());
                await myDatabase.destroy();
```

**Comment by jwallet** [comment]
Ok this a just a template, I dont use this one. All my schema have primary keys. Do you use a real SQLite storage when unit testing, because all queries using string works but not when using number and I guess it is the same issue with boolean. Switching to any other storage works great, like using the memory storage. 

Tested with expo-sqlite-storage which uses requery/sqlite-android and with react-native-sqlite-2

**Comment by pubkey** [comment]
My test runs once with `sqlite3` and once with the `websql` npm package.
So maybe this is a react-native specific problem or expo specific.

**Comment by jwallet** [comment]
Ok I think I found the issue, our collection use composite primary keys, if I turn that off and use the `id` field, I can retrieve documents uisng a number. When composite primary key is set, only string typed fields can be used.

Here is a proper example

```ts
// schema
const RxSheetSchema: RxJsonSchema<Sheet> = {
  keyCompression: true,
  indexes: ['updatedAt', ['year', 'weekNumber']],
  primaryKey: {
    key: 'key',
    fields: ['employeeId', 'year', 'weekNumber'],
    separator: '|',
  },
  additionalProperties: false,
  description: 'describes an employee week sheet',
  properties: {
    // ...other fields
    updatedAt: {
      type: 'number',
      minimum: 0,
      maximum: 99999999999999,
      multipleOf: 1,
    },
    employeeId: {
      maxLength: 36,
      type: 'string',
    },
    key: {
      maxLength: 100,
      type: 'string',
    },
    id: {
      maxLength: 100,
      type: 'string',
    },
    isDeleted: { type: 'boolean' },
    weekNumber: {
      type: 'number',
      minimum: 0,
      maximum: 53,
      multipleOf: 1,
    },
    year: {
      type: 'number',
      minimum: 0,
      maximum: 10000,
      multipleOf: 1,
    },
  },
  required: ['key', 'id', 'year', 'weekNumber', 'employeeId'],
  type: 'object',
  title: 'Schema Sheet',
  version: 0,
};

// example of key fields with value:
const fields = {
 weekNumber: 36,
 year: 2023,
 employeeId: 'eec26bab-b353-4ac0-842d-87e55e0ef7f5', // uuid v4
};

// example formatted key:
const key = 'eec26bab-b353-4ac0-842d-87e55e0ef7f5|2023|36'

// query looks like this. we use $and because the first part with employeeId is injected for all queries, the second part is the query from a component.
db.schema.find({ selector: {
 $and: [
  { employeeId: { $eq: 'eec26bab-b353-4ac0-842d-87e55e0ef7f5' }},
  { 
   weekNumber: { $eq: 13 },
   year: { $eq: 2023 },
  }
 ]
}});

// also tried a basic query, it failed too
db.schema.find({ selector: { year: { $eq: 2023 } } }).exec();
```


logs related to it, it failed to fetch a sheet, so it inserted a new one.
```bash
 LOG  ## RxStorage SQLite log: all(333) DONE
 LOG  ## RxStorage SQLite log: run(334) {"query":"BEGIN;","params":[],"context":{"method":"openSqliteTransaction","data":""}}
 LOG  ## RxStorage SQLite log: run(334) DONE
 LOG  ## RxStorage SQLite log: all(335) {"query":"SELECT data FROM \"sheet-0\" WHERE id IN (?)","params":["1934b59a-95c7-4f1a-a4ae-875dc6f33a09|2023|13"],"context":{"method":"bulkWrite","data":[{"document":{"|e":null,"key":"1934b59a-95c7-4f1a-a4ae-875dc6f33a09|2023|13","|j":[{"|k":"2023-03-20","id":"83467c42-d4bc-43ea-85be-6da368ca9889","|c":[],"|x":{"|f":false,"|q":"SheetEntry","id":"630c820f-1d26-4f10-9e6b-780e373bfd35"}}],"|p":"1934b59a-95c7-4f1a-a4ae-875dc6f33a09","id":"019e21f6-a4af-4434-aa4e-2d07f9518934","|t":false,"|J":1679274136379,"|K":13,"|P":2023,"_meta":{"lwt":1679274136386.01},"_deleted":false,"_rev":"1-mpfhpyrwir","_attachments":{}}}]}}
 LOG  ## RxStorage SQLite log: all(335) DONE
 LOG  ## RxStorage SQLite log: run(336) {"query":"COMMIT;","params":[],"context":{"method":"finishSqliteTransaction","data":"COMMIT"}}
 LOG  ## RxStorage SQLite log: run(336) DONE
DEBUG Not able to fetch timesheet "employeeId": "1934b59a-95c7-4f1a-a4ae-875dc6f33a09" "weekNumber": 13, "year": 2023 , inserting a new one...
DEBUG  RxDB: [CONFLICT] document in database "id": "eadc49a4-6d2e-4298-b526-ac55e0e63d05", "employeeId": "1934b59a-95c7-4f1a-a4ae-875dc6f33a09", "id": "f1cf2ea8-76d3-4195-84d2-0aca76da1c05", "key": "1934b59a-95c7-4f1a-a4ae-875dc6f33a09|2023|13", "weekNumber": 13, "year": 2023
ERROR  RxDB: [CONFLICT] sheet-insert Error: "Document update conflict. When changing a document you must work on the previous revision" 
```

**Comment by pubkey** [comment]
Since you get a conflict error, it more looks like you are working on an old revision of the document.

Can you add a minimal version of  your test to the query-correctness tests here? https://github.com/pubkey/rxdb/blob/master/test/unit/rx-storage-query-correctness.test.ts

**Comment by jwallet** [comment]
Yes that's the issue, I cannot get the document, so I insert one document if no document was returned. This can be done in the opposite direction too, I can insert a whole new document and I won't be able to get it using a property number until I remove my primary compsite key on the schema. 

This is not an issue with other storage or rxdb classic, even if I add a test there it won't throw an error. The issue appears only when querying directly to the Sqlite storage, if I use memory storage or memory-synced-storage-with-sqlite it's able to fetch the document.

I'm a bit stucked, since we don't have access to the closed code so it's not possible to add my failing unit test to the sqlite storage or any premium component like on rxdb classic. 

here is the use case but it will pass since other storage works fine:

```js
testCorrectQueries({
        testTitle: '$eq operator with composite primary key',
        data: [
            {
                id: 'one',
                key: 'one|1|1',
                string: 'one',
                number: 1,
                integer: 1,
            },
            {
                id: 'two',
                key: 'two|1|1',
                string: 'two',
                number: 1,
                integer: 1,
            },
            {
                id: 'three',
                key: 'one|2|1',
                string: 'one',
                number: 2,
                integer: 1,
            },
        ],
        schema: {
            version: 0,
            indexes: ['string', ['number', 'integer']],
            primaryKey: {
                key: 'key',
                fields: ['string', 'number', 'integer'],
                separator: '|',
            },
            type: 'object',
            properties: {
                key: {
                    maxLength: 100,
                    type: 'string',
                },
                id: {
                    maxLength: 100,
                    type: 'string',
                },
                string: {
                    maxLength: 50,
                    type: 'string',
                },
                number: {
                    type: 'number',
                    minimum: 0,
                    maximum: 100,
                    multipleOf: 1,
                },
                integer: {
                    type: 'integer',
                    minimum: 0,
                    maximum: 100,
                    multipleOf: 1,
                },
            },
            required: ['id', 'key', 'string', 'number', 'integer'],
        },
        queries: [
            {
                info: '$eq primary key',
                query: {
                    selector: {
                        id: {
                            $eq: 'one',
                        },
                    },
                    sort: [{ id: 'asc' }],
                },
                expectedResultDocIds: ['one|1|1'],
            },
            {
                info: '$eq by key',
                query: {
                    selector: {
                        key: {
                            $eq: 'one|1|1',
                        },
                    },
                    sort: [{ id: 'asc' }],
                },
                expectedResultDocIds: ['one|1|1'],
            },
            {
                info: '$eq by composite key fields',
                query: {
                    selector: {
                        $and: [
                            {
                                string: {
                                    $eq: 'one',
                                },
                            },
                            {
                                number: {
                                    $eq: 1,
                                },
                                integer: {
                                    $eq: 1,
                                },
                            },
                        ],
                    },
                    sort: [{ number: 'desc', integer: 'desc' }],
                },
                expectedResultDocIds: ['one|1|1'],
            },
        ],
    });
```

**Comment by pubkey** [comment]
I tried to add your tests to the rxdb test suite but it failed even on the memory adapter, I will check.
All tests run on the premium storages in the background, so I can then see what is going wrong.

**Comment by pubkey** [comment]
The error I get:

```
WRONG QUERY RESULTS FROM .query(): $eq by key
{
    "info": "$eq by key",
    "query": {
        "selector": {
            "key": {
                "$eq": "one|1|1"
            }
        },
        "sort": [
            {
                "id": "asc"
            }
        ]
    },
    "expectedResultDocIds": [
        "one|1|1"
    ]
}
    1) $eq operator with composite primary key


  120 passing (9s)
  1 failing

  1) rx-storage-query-correctness.test.ts
       $eq operator with composite primary key:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  [
    'one|1|1',
+   'one|2|1',
+   'two|1|1'
  ]
      + expected - actual

       [
         "one|1|1"
      -  "one|2|1"
      -  "two|1|1"
       ]
      
      at _loop (test/unit/rx-storage-query-correctness.test.ts:163:28)
      at Context.<anonymous> (test/unit/rx-storage-query-correctness.test.ts:111:50)


```

**Comment by jwallet** [comment]
it should fetch correctly on memory storage, I'm able to get a document by key now, since the query by fields is not working anymore because some fields contains number. Maybe if the test uses fake uuid for `id`, the results might be different ?

```
data: [
            {
                id: 'b6dfd865-6dd7-4089-9fad-a99ef413d082',
                key: 'one|1|1',
                string: 'one',
                number: 1,
                integer: 1,
            },
            {
                id: 'b01db6ed-7f7f-4fa3-a1c5-38a9b0d7294a',
                key: 'two|1|1',
                string: 'two',
                number: 1,
                integer: 1,
            },
            {
                id: 'efd0a29a-ca35-42b4-bb91-b0c04b4a8628',
                key: 'one|2|1',
                string: 'one',
                number: 2,
                integer: 1,
            },
        ],
```

**Comment by jwallet** [comment]
you may remove or change query by primary key, I don't personally use it, but I added for testing purpose.

**Comment by pubkey** [comment]
So I have run these tests with the sqlite storage now and everything works correctly.

**Comment by pubkey** [comment]
I am not sure how to proceed. If I cannot reproduce the problem, I will not touch anything.

**Comment by jwallet** [comment]
@pubkey  turns out our ios database works just fine. Thanks a lot for the support, sorry I did not catch it earlier. 

So the issue is probably in https://github.com/requery/sqlite-android because in my wrapper I have no code that will make queries by number work when the primary key is a field versus a composite one with fields.

**Comment by pubkey** [comment]
Ok. Ping me if there is any way I can help.
Your tests still provided value since they detected an error in the query planner which is now fixed.
