### ISSUE TITLE
Error: missing value from map 1

### ISSUE THREAD

**Issue by LeXaMeN** [pubkey/rxdb#4748]
An error is thrown when updating data.

```
{
    "eventId": "qgdzjsbkhl|0|1|4-rrqbrngzer",
    "documentId": 1,
    "collectionName": "lists",
    "startTime": 1684760744611.01,
    "endTime": 1684760744617.01,
    "isLocal": false,
    "operation": "UPDATE",
    "documentData": {
        "id": 1,
        "createdAt": "2022-06-20T02:18:34.172Z",
        "updatedAt": "2022-09-21T09:59:14.415Z",
        "name": "ab",
        "order": 1,
        "isDefault": false,
        "_meta": {
            "lwt": 1684760744610.01
        },
        "_deleted": false,
        "_attachments": {},
        "_rev": "4-rrqbrngzer"
    },
    "previousDocumentData": {
        "id": 1,
        "createdAt": "2022-06-20T02:18:34.172Z",
        "updatedAt": "2022-09-21T09:59:14.415Z",
        "name": "ab",
        "order": 1,
        "isDefault": false,
        "_meta": {
            "lwt": 1684760476277.01
        },
        "_deleted": false,
        "_attachments": {},
        "_rev": "3-crjnmnbgjl"
    }
}
```

```
utils-map.js:4 Uncaught (in promise) Error: missing value from map 1
    at getFromMapOrThrow (utils-map.js:4:1)
    at eval (incremental-write.js:93:1)
    at Array.map (<anonymous>)
    at IncrementalWriteQueue.triggerRun (incremental-write.js:91:1)
```
Your code is sending a string key
![image](https://github.com/pubkey/rxdb/assets/31878437/54f3f1cb-bcc3-40e0-9e70-4784ff7e5038)

But the map holds a numeric key
![image](https://github.com/pubkey/rxdb/assets/31878437/a420e541-6b08-4611-b756-780a1ee23757)

Your code is trying to get some metadata
![image](https://github.com/pubkey/rxdb/assets/31878437/6a202f6a-0bf5-4e98-8676-531b1a412d0f)

**Comment by pubkey** [comment]
Please make a PR with a failing unit test.

**Comment by LeXaMeN** [comment]
I used bulkUpsert to create documents.
And when I re-call this function to update with the same data set, this error is thrown.
I also tried with doc.incrementalPatch - same error.

**Comment by LeXaMeN** [comment]
```
import { App, Plugin, inject } from 'vue';
import { createRxDatabase, RxCollection, RxDatabase } from 'rxdb';
import { getRxStorageDexie } from 'rxdb/plugins/storage-dexie';

export const RxDBPlugin: Plugin = {
  async install(app: App, options: () => void) {
    
    const database = await createRxDatabase({
      name: 'fixdb',
      storage: getRxStorageDexie(),
      // password: 'myPassword',
      multiInstance: true,
      eventReduce: true,
      // cleanupPolicy: {}
    });

    const listSchemaV0 = {
      title: 'lists schema',
      version: 0,
      primaryKey: 'id',
      type: 'object',
      properties: {
        id: {
          type: 'integer',
          multipleOf: 1,
          minimum: 1,
          maximum: 2147483647
        },
        createdAt: {
          type: 'string',
          pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{3,}Z$'
        },
        updatedAt: {
          type: 'string',
          pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{3,}Z$'
        },
        workspaceId: {
          type: 'integer',
          multipleOf: 1,
          minimum: 1,
          maximum: 2147483647
        },
        assigneeList: {
          type: 'array',
          uniqueItems: true,
          items: {
            primaryKey: 'id',
            type: 'object',
            properties: {
              id: {
                type: 'integer',
                multipleOf: 1,
                minimum: 1,
                maximum: 2147483647
              },
              userName: {
                type: 'string'
              },
              email: {
                type: 'string'
              },
              phone: {
                type: 'string'
              }
            },
            required: ['userName', 'email'],
          }
        },
        name: {
          type: 'string'
        },
        order: {
          type: 'integer',
          multipleOf: 1,
          minimum: 1,
          maximum: 2147483647
        },
        isDefault: {
          type: 'boolean',
          default: false
        }
      },
      required: ['createdAt', 'updatedAt', 'workspaceId', 'order'],
      //indexes: ['workspaceId', 'order']
    }

    const collections  = await database.addCollections({
      lists: {
        schema: listSchemaV0,
        // statics: {},
        // methods: {},
        // attachments: {},
        // options: {},
        // migrationStrategies: {},
        autoMigrate: true,
        // cacheReplacementPolicy: function(){},
        // conflictHandler: function(){}
      }
    });

    collections.lists.$.subscribe(changeEvent => console.dir(changeEvent));

    app.config.globalProperties.$db = database;
  }
}
```

**Comment by LeXaMeN** [comment]
@pubkey just fix utils-map.js for use number keys

**Comment by LeXaMeN** [comment]
@pubkey I try use string key

```
id: {
  // type: 'integer',
  // multipleOf: 1,
  // minimum: 1,
  // maximum: 2147483647
  type: 'string',
  maxLength: 10
},
```

The same error occurs

**Comment by LeXaMeN** [comment]
@pubkey I understood that primary key as number is not supported...
But this is silly, since indexes as numbers are supported.

**Comment by LeXaMeN** [comment]
Now I have to make all numeric keys string before saving. It's stupid
