### ISSUE TITLE
`hasOwnProperty is not a function` in plugins/utils-object.ts

### ISSUE THREAD

**Issue by emil14** [pubkey/rxdb#5382]
This is how object in a collection was changed:

```js
{
    type: 'doc',
    content: [
        {
            type: 'text',
            content: '#'
        }
    ]
}

->

{
    type: 'doc',
    content: [
        {
            type: 'heading',
            attrs: {
                level: 1
            },
            content: []
        }
    ]
}
```

For doing so I did

```ts
await existingInDB.incrementalModify((doc: RxDocument<Document>) => ({
	...doc,
	data: newContent,
}))
```

I also tried `modify` and `update`, nothing helps.

Despite this error everything looks working but when I then delete this document like this

```ts
await collection.docs.findOne(id).remove()
```

I got conflict

```
rx-error.ts:112 Uncaught (in promise) RxError (CONFLICT): RxError (CONFLICT):
Document update conflict. When changing a document you must work on the previous revision
Given parameters: {
collection:"docs"
id:"e2ba1ff0-79f6-48ea-9818-f4ee196e70ba"
writeError:{
  "isError": true,
  "status": 409,
  "documentId": "e2ba1ff0-79f6-48ea-9818-f4ee196e70ba",
  "writeRow": {
    "document": {
      "id": "e2ba1ff0-79f6-48ea-9818-f4ee196e70ba",
      "data": {
        "type": "doc",
        "content": [
          {
            "type": "paragraph",
            "content": [
              {
                "type": "text",
                "text": "#"
              }
            ]
          }
        ]
      },
      "_meta": {
        "lwt": 1702569841972.01
      },
      "_deleted": true,
      "_attachments": {},
      "_rev": "13-wzlhzxuhoy"
    },
    "previous": {
      "id": "e2ba1ff0-79f6-48ea-9818-f4ee196e70ba",
      "data": {
        "type": "doc",
        "content": [
          {
            "type": "paragraph",
            "content": [
              {
                "type": "text",
                "text": "#"
              }
            ]
          }
        ]
      },
      "_meta": {
        "lwt": 1702569260031.01
      },
      "_deleted": false,
      "_attachments": {},
      "_rev": "12-wzlhzxuhoy"
    }
  },
  "documentInDb": {
    "id": "e2ba1ff0-79f6-48ea-9818-f4ee196e70ba",
    "data": {
      "type": "doc",
      "content": [
        {
          "type": "heading",
          "attrs": {
            "level": 1
          },
          "content": [
            {
              "type": "text",
              "text": " "
            }
          ]
        }
      ]
    },
    "_meta": {
      "lwt": 1702569356442.01
    },
    "_deleted": false,
    "_attachments": {},
    "_rev": "14-wzlhzxuhoy"
  }
}
data:{
  "id": "e2ba1ff0-79f6-48ea-9818-f4ee196e70ba",
  "data": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "#"
          }
        ]
      }
    ]
  },
  "_meta": {
    "lwt": 1702569260031.01
  },
  "_deleted": true,
  "_attachments": {},
  "_rev": "12-wzlhzxuhoy"
}}
    at newRxError (rx-error.ts:112:12)
    at throwIfIsStorageWriteError (rx-storage-helper.ts:128:19)
    at rx-document.ts:381:17
    at async Object.delete (documents.ts:41:3)
    at async remove (Navbar.svelte:17:9)
await in (anonymous) (async)		
click_handler	@	Navbar.svelte:39
Show 3 more frames
```

Look's like this `hasOwnProperty` problem has something to do with this conflict. Here are the screenshots from my investigation. I understood that most of the time everything is ok and this util function operates on object with hasOwnProperty field but my `attrs` object does not have that prototype for some reason:

<img width="493" alt="Screen Shot 2023-12-14 at 21 24 27" src="https://github.com/pubkey/rxdb/assets/6453537/d06862ab-92b3-440e-8cb3-7cbe157d4e4f">

<img width="1512" alt="Screen Shot 2023-12-14 at 21 59 20" src="https://github.com/pubkey/rxdb/assets/6453537/0abadf8c-3ed2-4d57-9c34-db27d0f37dd8">

I might say "just create normal objects" but the thing is I'm not the one who creating it. For instance I use TipTap library and library is responsible for that. I can't intercept every object from that library. I think you need to modify how this function works (no matter is this the root of my problem or not), e.g. using `Object.prototype.hasOwnProperty` instead of how you do that now.

This problem is critical to my app so please help.

Thank you!

**Comment by pubkey** [comment]
You can only store plain json objects into rxdb. If you have another type of instance, transform it to plain json first.

**Comment by emil14** [comment]
@pubkey but I use plain json

**Comment by emil14** [comment]
@pubkey 

Here's a fix, just 1 line of code https://github.com/pubkey/rxdb/pull/5391

The problem with your code described here https://eslint.org/docs/latest/rules/no-prototype-builtins

**Comment by pubkey** [comment]
Fixed here https://github.com/pubkey/rxdb/pull/5398
