### ISSUE TITLE
[BUG] Can't run RxDB Memory on Node.js v11.0.0: broadcast-channel issue

### ISSUE THREAD

**Issue by tiloio** [pubkey/rxdb#850]
## Case
Moin moin, I get an exception when I run RxDB on Node.js.
There is a broadcast-channel excpetion, I can't figure it out for now.

## Issue
I cant run RxDB on Node.js, I get the following exception:
```
C:\sources\RxDB-test\server\node_modules\broadcast-channel\src\methods\node.js:617
    channelState.socketEE.emitter.removeAllListeners();
                          ^

TypeError: Cannot read property 'emitter' of undefined
    at close (C:\sources\RxDB-test\server\node_modules\broadcast-channel\src\methods\node.js:617:27)
    at state.removeUnload.unload.add (C:\sources\RxDB-test\server\node_modules\broadcast-channel\src\methods\node.js:386:40)
    at C:\sources\RxDB-test\server\node_modules\unload\dist\lib\index.js:51:19
    at Set.forEach (<anonymous>)
    at runAll (C:\sources\RxDB-test\server\node_modules\unload\dist\lib\index.js:50:13)
    at process.<anonymous> (C:\sources\RxDB-test\server\node_modules\unload\dist\lib\node.js:38:12)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:622:27)
```

## Info
  - Environment: Node.js v11.0.0 on Windows 10 (Build 17134.345)
  - Adapter: MemoryAdapter

My dependencies:
  ```js
   {"babel-polyfill": "^6.26.0",
    "pouchdb-adapter-memory": "^7.0.0",
    "rxdb": "^8.0.3",
    "rxjs": "^6.3.3" }
```
## Code

```js
require('babel-polyfill');
const RxDB = require("rxdb");

// add the memory-adapter
const MemoryAdapter = require("pouchdb-adapter-memory");
RxDB.plugin(MemoryAdapter);

// to use awaits and avoid then chaining
(async () => {
  // create database
  await RxDB.create({
    name: "mydb",
    adapter: "memory"
  });

})().catch(e => {
    console.error('error on custom code', e);
});;
```

**Comment by tiloio** [comment]
@pubkey I have the same Issue with Node.js v10.13.0 (the current LTS-Version).
You said in [pubkey/broadcast-channel#6](https://github.com/pubkey/broadcast-channel/issues/6) that only slow devices are affected. These are my specs (and I don't think that is slow...):
- Intel Core i7-6700HQ CPU @ 2.60 GHz
- 16.0 GB RAM
- SSD etc.

**Comment by pubkey** [comment]
@tiloio I think I might have fixed this. Can you please try the latest [rxdb from the commit hash](https://rxdb.info/install.html#latest)

**Comment by pubkey** [comment]
Great. I'm closing this.
