### ISSUE TITLE
[BUG] Can't run RxDBServerPlugin on Node.js

### ISSUE THREAD

**Issue by tiloio** [pubkey/rxdb#852]
## Case
If I run a RxDB on Node.js the application closes immediately after execution.
The process is not waiting for any requests.

I used the example [Using the Server Plugin](https://rxdb.info/tutorials/server.html) for my code.

## Issue
Node.js process closes after execution.
```
[19:30:00] C:\sources\RxDB-test\server>node .
[19:30:00] Server should run now...

[19:30:00] C:\sources\RxDB-test\server>
```

## Info
  - Environment: Node.js v10.13.0
  - Adapter: (MemoryAdapter

## Code

```js
require("babel-polyfill");
const RxDB = require("rxdb");

// add the server-plugin
const RxDBServerPlugin = require("rxdb/plugins/server");
RxDB.plugin(RxDBServerPlugin);

// add the memory-adapter
const MemoryAdapter = require("pouchdb-adapter-memory");
RxDB.plugin(MemoryAdapter);

const mySchema = {
  version: 0,
  type: "object",
  properties: {
    key: {
      type: "string",
      primary: true
    },
    value: {
      type: "string"
    }
  }
};

// to use awaits and avoid then chaining
(async () => {
  // create database
  const db = await RxDB.create({
    name: "mydb",
    adapter: "memory"
  });

  await db.collection({
    name: "items",
    schema: mySchema
  });

  // insert one document
  await db.items.insert({
    key: "foo",
    value: "bar"
  });

  const serverState = db.server({
    path: "/db", // (optional)
    port: 3000, // (optional)
    cors: true // (optional), enable CORS-headers
  });

  console.log('Server should run now...');
  
})().catch(e => {
  console.error("error on custom code", e);
});
```

**Comment by tiloio** [comment]
If I only run this:
```js
const RxDB = require("rxdb");
const express = require("express");

// add the memory-adapter
const MemoryAdapter = require("pouchdb-adapter-memory");
RxDB.plugin(MemoryAdapter);

// create database
RxDB.create({
  name: "mydb",
  adapter: "memory"
});

const app = express();
app.get("/", function(req, res) {
  res.send("Hello World!");
});

app.listen(3000, function() {
  console.log("Example app listening on port 3000!");
});
```

The express app is also not running. (I tried it before, after and in the _"then"_ path of the create).
If I remove the create, the express app runs as expected.

**Comment by pubkey** [comment]
Hmm. I copied your code into a js-file and run it. Everything works there. Which os do you have?

**Comment by pubkey** [comment]
You are not the first one with this problem. I also had it once but somehow it disapeared. It would be nice if you could help me to pin this down and fix it once and for all.

**Comment by pubkey** [comment]
Ah. I think this happens when the port is already used. I will investigate..

**Comment by tiloio** [comment]
I am running it on Windows 10.
I switched the port already, which did not change anything...

**Comment by pubkey** [comment]
Hi @tiloio I think I have fixed this problem.
Can you install rxdb via the latest master? You can do this by changing it to this in your package.json:

```json
  "dependencies": {
      "rxdb": "git+https://git@github.com/pubkey/rxdb.git#47726e8f3a32bde0b9c6517eded7d743165ead1a"
  }
```

This might not directly fix  your problem, but it does no longer swallow the exception so you can see what is wrong.

**Comment by tiloio** [comment]
I got this error now:
```js
$ node .
Server should run now...
Trace: { Error: connect ENOENT \\.\pipe\C:\Users\Tilo\AppData\Local\Temp\pubkey.bc\Ab18f677215e743067bfd\rdrs\0jdl5y0pb8.s
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address:
   '\\\\.\\pipe\\C:\\Users\\Tilo\\AppData\\Local\\Temp\\pubkey.bc\\Ab18f677215e743067bfd\\rdrs\\0jdl5y0pb8.s' }
    at C:\sources\RxDB-test\server\node_modules\unload\dist\lib\node.js:39:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

There is no `0jdl5y0pb8.s` but a `0jdl5y0pb8.json` File, which containse this:
` {"time":1541697558190649}`
