### ISSUE TITLE
Unable to save with 'has additional properties' error.

### ISSUE THREAD

**Issue by rmisio** [pubkey/rxdb#916]
## Case
maybe a bug..?

## Issue
An upsert attempt is failing with a 'has additional properties' error.

## Info
  - Environment: chrome browser
  - Adapter: IndexedDB
  - Stack: React

## Code

```
db.profile.upsert(profileData);
```

fails with:

```
construct.js:30 Uncaught (in promise) RxError: RxError:
object does not match schema
Given parameters: {
errors:[
  {
    "field": "data",
    "message": "has additional properties"
  }
]
schemaPath:""
obj:{
  "moderatorInfo": null,
  "contactInfo": null,
  "colors": null,
  "avatarHashes": null,
  "name": "city slicker",
  "shortDescription": "",
  "peerID": "QmRHvW41Ga6wQuayQNbrhwrTghasabxwWwqmT5hrWXQLoj",
  "about": "",
  "handle": "",
  "location": "",
  "moderator": false,
  "nsfw": false,
  "vendor": false
}
schema:{
  "title": "User profile schema",
  "description": "Database schema for the profile of a user",
  "version": 0,
  "type": "object",
  "properties": {
    "peerID": {
      "type": "string",
      "primary": true
    },
    "handle": {
      "type": "string",
      "encrypted": true,
      "default": ""
    },
    "name": {
      "type": "string",
      "encrypted": true
    },
    "location": {
      "type": "string",
      "encrypted": true,
      "default": ""
    },
    "about": {
      "type": "string",
      "encrypted": true,
      "default": ""
    },
    "shortDescription": {
      "type": "string",
      "encrypted": true,
      "default": ""
    },
    "nsfw": {
      "type": "boolean",
      "encrypted": true,
      "default": false
    },
    "vendor": {
      "type": "boolean",
      "encrypted": true,
      "default": false
    },
    "moderator": {
      "type": "boolean",
      "encrypted": true,
      "default": false
    },
    "moderatorInfo": {
      "type": [
        "object",
        "null"
      ],
      "encrypted": true
    },
    "contactInfo": {
      "type": [
        "object",
        "null"
      ],
      "encrypted": true,
      "properties": {
        "website": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "social": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "username": {
                "type": "string"
              },
              "proof": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "colors": {
      "type": [
        "object",
        "null"
      ],
      "encrypted": true,
      "properties": {
        "primary": {
          "type": "string"
        },
        "secondary": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "highlight": {
          "type": "string"
        },
        "highlightText": {
          "type": "string"
        }
      }
    },
    "_rev": {
      "type": "string",
      "minLength": 1
    },
    "_attachments": {
      "type": "object"
    }
  },
  "avatarHashes": {
    "type": [
      "object",
      "null"
    ],
    "properties": {
      "tiny": {
        "type": "string"
      },
      "small": {
        "type": "string"
      },
      "medium": {
        "type": "string"
      },
      "large": {
        "type": "string"
      },
      "original": {
        "type": "string"
      }
    }
  },
  "required": [
    "peerID",
    "name"
  ],
  "additionalProperties": false,
  "keyCompression": false,
  "compoundIndexes": []
}}
    at Object.newRxError (http://localhost:3000/static/js/28.chunk.js:143108:10)
    at RxSchema.validate (http://localhost:3000/static/js/28.chunk.js:139524:61)
    at http://localhost:3000/static/js/28.chunk.js:140732:21
```

The only data I'm actually passing it is:

```
{
  "moderatorInfo": null,
  "contactInfo": null,
  "colors": null,
  "avatarHashes": null,
  "name": "city slicker",
  "shortDescription": "",
  "peerID": "QmRHvW41Ga6wQuayQNbrhwrTghasabxwWwqmT5hrWXQLoj"
}
```

The rest should be coming from defaults defined in the schema.

I'm not seeing what property it's getting which is not in the schema...? Is that what the error means?

**Comment by rmisio** [comment]
Looks like I declared `avatarHashes` outside of the `properties` key in the schema.
